name: "Lint, Test & Deploy"
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        run: npm lint
      - name: Test
        run: npm test
      - name: Build code
        run: npm build